name: Auto Sync iStoreOS ARM to Docker Hub

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: '强制构建镜像'
        required: false
        default: 'false'
        type: boolean
  schedule:
    - cron: '0 10 * * *' # 每天10点检测一次

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_TAG: latest
  ISTOREOS_URL: https://fw.koolcenter.com/iStoreOS/armsr/

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget curl qemu-utils kpartx \
            e2fsprogs tar gzip zstd bzip2 util-linux parted \
            coreutils

      - name: Check latest version
        id: checkver
        run: |
          latest_file=$(curl -s $ISTOREOS_URL | grep -oE 'istoreos-[^ ]+efi.img.gz' | head -n1)
          echo "latest_file=$latest_file" >> $GITHUB_ENV

          # 提取版本信息
          full_version=$(echo $latest_file | sed -n 's/istoreos-\([0-9.]*\)-\([0-9]*\)-armsr-squashfs-combined-efi\.img\.gz/\1-\2/p')
          software_version=$(echo $latest_file | sed -n 's/istoreos-\([0-9.]*\)-\([0-9]*\)-armsr-squashfs-combined-efi\.img\.gz/\1/p')
          version_tag=$(echo $latest_file | sed -n 's/istoreos-\([0-9.]*\)-\([0-9]*\)-armsr-squashfs-combined-efi\.img\.gz/\2/p')

          echo "full_version=$full_version" >> $GITHUB_ENV
          echo "software_version=$software_version" >> $GITHUB_ENV
          echo "version_tag=$version_tag" >> $GITHUB_ENV

          echo "Latest file: $latest_file"
          echo "Full version: $full_version"
          echo "Software version: $software_version"
          echo "Version tag: $version_tag"

          # 检查是否已存在该版本的标签，除非强制构建
          if [ "${{ github.event.inputs.force_build }}" != "true" ]; then
            # 获取所有远程标签
            git fetch --tags
            
            # 使用精确匹配检查标签是否存在
            if git tag --list | grep -Fx "$full_version"; then
              echo "Version $full_version already exists, exiting."
              echo "skip_build=true" >> $GITHUB_ENV
            else
              echo "skip_build=false" >> $GITHUB_ENV
            fi
          else
            echo "Force build enabled, proceeding..."
            echo "skip_build=false" >> $GITHUB_ENV
          fi

      - name: Download latest img.gz
        if: env.skip_build == 'false'
        run: |
          echo "Downloading: ${ISTOREOS_URL}${latest_file}"
          wget ${ISTOREOS_URL}${latest_file} -O istoreos.img.gz

          # 验证下载的文件
          echo "Downloaded file size: $(stat -c%s istoreos.img.gz) bytes"

          # 验证文件大小是否合理 (应该大于50MB)
          file_size=$(stat -c%s istoreos.img.gz)
          if [ "$file_size" -lt 52428800 ]; then
            echo "Downloaded file size is too small: $file_size bytes"
            exit 1
          fi

          # 检查文件头是否为gzip格式
          file_header=$(head -c 2 istoreos.img.gz | xxd -p)
          if [ "$file_header" != "1f8b" ]; then
            echo "File does not have gzip header, retrying download..."
            rm -f istoreos.img.gz
            wget ${ISTOREOS_URL}${latest_file} -O istoreos.img.gz
            
            # 再次验证大小和头部
            file_size=$(stat -c%s istoreos.img.gz)
            if [ "$file_size" -lt 52428800 ]; then
              echo "Retry download still too small: $file_size bytes"
              exit 1
            fi
            
            file_header=$(head -c 2 istoreos.img.gz | xxd -p)
            if [ "$file_header" != "1f8b" ]; then
              echo "File still does not have gzip header after retry."
              echo "File contents preview:"
              head -c 100 istoreos.img.gz | xxd
              exit 1
            fi
          fi

          echo "File has valid gzip header, proceeding with extraction..."

          echo "File validation successful"

      - name: Extract rootfs from img.gz
        if: env.skip_build == 'false'
        run: |
          # 解压镜像文件，可能会有尾随垃圾数据的警告，但这是正常的
          echo "Extracting image file..."
          echo "Note: 'trailing garbage ignored' warnings are normal and can be safely ignored"

          # 使用更宽松的解压策略
          gunzip -c istoreos.img.gz > istoreos.img 2>&1 | tee extraction.log || true

          # 检查解压结果
          if [ -f "istoreos.img" ]; then
            img_size=$(stat -c%s istoreos.img)
            echo "Extracted image file size: $img_size bytes"
            
            # 验证文件大小是否合理 (应该大于200MB解压后)
            if [ "$img_size" -gt 209715200 ]; then
              echo "Extraction successful - file size is reasonable"
            else
              echo "Warning: Extracted file seems too small: $img_size bytes"
              echo "Extraction log:"
              cat extraction.log
              echo "File listing:"
              ls -la istoreos.*
              exit 1
            fi
          else
            echo "Extraction failed - no output file created"
            echo "Extraction log:"
            cat extraction.log
            exit 1
          fi

          # 使用 NBD 设备挂载镜像
          sudo modprobe nbd max_part=8

          echo "Connecting NBD device..."
          if sudo qemu-nbd --connect=/dev/nbd0 --format=raw istoreos.img; then
            echo "NBD device connected successfully"
          else
            echo "Failed to connect NBD device"
            exit 1
          fi

          sleep 3
          sudo partprobe /dev/nbd0

          # 列出分区信息
          sudo fdisk -l /dev/nbd0

          # 创建挂载点并尝试挂载各个分区
          mkdir -p rootfs

          # 尝试挂载第二个分区（通常是根文件系统）
          if sudo mount -o ro /dev/nbd0p2 rootfs 2>/dev/null; then
            echo "Successfully mounted /dev/nbd0p2"
          elif sudo mount -o ro /dev/nbd0p1 rootfs 2>/dev/null; then
            echo "Successfully mounted /dev/nbd0p1"
          else
            echo "Failed to mount any partition, trying all available partitions..."
            for part in /dev/nbd0p*; do
              if [ -e "$part" ]; then
                echo "Trying to mount $part"
                if sudo mount -o ro "$part" rootfs 2>/dev/null; then
                  echo "Successfully mounted $part"
                  break
                fi
              fi
            done
          fi

          # 检查是否成功挂载了根文件系统
          if [ -d "rootfs/etc" ] && [ -d "rootfs/usr" ]; then
            echo "Root filesystem detected"
            ls -la rootfs/ | head -10
            
            # 创建 rootfs.tar
            sudo tar -cf rootfs.tar -C rootfs .
            sudo chown $(id -u):$(id -g) rootfs.tar
            
            echo "rootfs.tar created successfully"
            ls -lh rootfs.tar
          else
            echo "Failed to find valid root filesystem"
            ls -la rootfs/
            exit 1
          fi

          # 清理
          sudo umount rootfs
          sudo qemu-nbd --disconnect /dev/nbd0

      - name: Upload Artifact
        if: env.skip_build == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: istoreos-arm-rootfs-${{ env.version_tag }}
          path: rootfs.tar
          retention-days: 1

      - name: Set up QEMU
        if: env.skip_build == 'false'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.skip_build == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: env.skip_build == 'false'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: env.skip_build == 'false'
        run: |
          mkdir -p docker-build
          cp rootfs.tar docker-build/
          cd docker-build

          cat > Dockerfile <<'EOF'
          FROM scratch
          ADD rootfs.tar /
          CMD ["/sbin/init"]
          EOF

          echo "Building Docker images with tags:"
          echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}"
          echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.full_version }}"
          echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.software_version }}"
          echo "- ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version_tag }}"

          docker buildx build --platform linux/arm64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.full_version }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.software_version }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version_tag }} \
            --push .

      - name: Create Release
        if: env.skip_build == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.full_version }}
          name: iStoreOS ARM Release ${{ env.full_version }}
          body: |
            ## iStoreOS ARM 自动构建

            ### 版本信息
            - **完整版本**: ${{ env.full_version }}
            - **软件版本**: ${{ env.software_version }}
            - **时间戳**: ${{ env.version_tag }}
            - **镜像名称**: ${{ env.latest_file }}
            - **构建时间**: ${{ github.run_number }}

            ### Docker 镜像

            可用标签:
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest`
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.full_version }}`
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.software_version }}`
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version_tag }}`

            ### 使用方法

            ```bash
            # 拉取最新镜像
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            # 运行容器
            docker run -it --privileged ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ```

            ### 原始镜像下载

            - **来源**: [iStoreOS 官方下载](https://fw.koolcenter.com/iStoreOS/armsr/)
            - **文件**: ${{ env.latest_file }}

            本版本由 GitHub Actions 自动构建，基于原生 iStoreOS 根文件系统构建。

      - name: Clean up artifacts
        if: always()
        run: |
          # 确保卸载所有挂载点
          sudo umount rootfs 2>/dev/null || true

          # 确保断开NBD设备
          sudo qemu-nbd --disconnect /dev/nbd0 2>/dev/null || true

          # 清理文件
          rm -f istoreos.img.gz istoreos.img rootfs.tar
          sudo rm -rf rootfs docker-build
